cash_flow/urls.py
from django.contrib import admin
from django.urls import include, path


                            #+++++++++++основной url++++++++++
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace = 'main'))
]

if DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

main/urls.py
from django.urls import path
from main import views

 
app_name = 'main'


                   #+++++++++++Транзакциии url++++++++++
urlpatterns = [
     path('', views.transaction_list, name='transaction_list'),
    path('create/', views.transaction_create, name='transaction_create'),
    path('<int:pk>/edit/', views.transaction_edit, name='transaction_edit'),
    path('<int:pk>/delete/', views.transaction_delete, name='transaction_delete'),
                             #+++++++++++справочник url++++++++++
    path('guide/', views.guide_list, name='guide_list'),
                            #+++++++++++категория url++++++++++
    path('guide/category/create/', views.category_create, name='category_create'),
    path('guide/category/<int:pk>/edit/', views.category_edit, name='category_edit'),
    path('guide/category/<int:pk>/delete/', views.category_delete, name='category_delete'),
                             #+++++++++++Подкатегория url++++++++++
    path('guide/subcategory/create/', views.subcategory_create, name='subcategory_create'),
    path('guide/subcategory/<int:pk>/edit/', views.subcategory_edit, name='subcategory_edit'),
    path('guide/subcategory/<int:pk>/delete/', views.subcategory_delete, name='subcategory_delete'),
                            #+++++++++++тип url++++++++++
    path('guide/type/create/', views.transtype_create, name='transtype_create'),
    path('guide/type/<int:pk>/delete/', views.transaction_delete, name='transtype_delete'),
    path('guide/type/<int:pk>/edit/', views.transtype_edit, name='transtype_edit'),
                            #+++++++++++статус url++++++++++
    path('guide/status/create/', views.status_create, name='status_create'),
    path('guide/status/<int:pk>/edit/', views.status_edit, name='status_edit'),
    path('guide/status/<int:pk>/delete/', views.status_delete, name='status_delete'),
]

main/models.py
from django.db import models
from django.utils import timezone

 
            #++++++создаем модели++++ 
            #++++++ модель статус++++ 
class Status(models.Model):
    name = models.CharField(max_length=150, unique=True)
    
    class Meta:
        # db_table ='status'
        verbose_name ='статус'
        verbose_name_plural = 'статусы'
    
    def __str__(self):
        return self.name
    
            #++++++ модель тип транзакции++++ 
class TransactionType(models.Model):
    name = models.CharField(max_length=150, unique=True)
    
    
    class Meta:
        # db_table ='transactiontype'
        verbose_name ='тип транзакции'
        verbose_name_plural = 'типы транзакции'
    
    def __str__(self):
        return self.name
    
            #++++++ модель категория++++ 
class Category(models.Model):
    name = models.CharField(max_length=150)
    transaction_type = models.ForeignKey(TransactionType, on_delete=models.CASCADE, related_name="categories")
    
    class Meta:
        # db_table ='category'
        verbose_name ='категория'
        verbose_name_plural = 'категории'
    
    
    def __str__(self):
        return f'{self.name} ({self.transaction_type.name})'
    
            #++++++ модель подкатегория++++ 
class SubCategory(models.Model):
    name = models.CharField(max_length=150)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="subcategories")
    
    class Meta:
        # db_table ='subcategory'
        verbose_name ='подкатегория'
        verbose_name_plural = 'подкатегории'
    
    def __str__(self):
        return f"{self.name} -> {self.category.name}"
    
    
                    #++++++ модель транзакция++++
class Transaction(models.Model):
    date = models.DateField(default=timezone.now )
    status = models.ForeignKey(Status, on_delete=models.PROTECT, related_name="transactions")
    transaction_type = models.ForeignKey(TransactionType, on_delete=models.PROTECT, related_name="transactions")
    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name="transactions")
    subcategory = models.ForeignKey(SubCategory, on_delete=models.PROTECT, related_name="transactions")
    summa = models.DecimalField(max_digits=14, decimal_places=2)
    comment = models.TextField(blank=True, null=True)  # необязателен к заполнению
    
    class Meta:
        # db_table ='transaction'
        verbose_name ='транзакция'
        verbose_name_plural = 'транзакции'
    
    
    def __str__(self):
        return f"{self.date} | {self.transaction_type.name} | {self.summa} рублей"
    

main/forms.py
from tabnanny import verbose
from django import forms
from main.models import Category, Status, SubCategory, Transaction, TransactionType


# ++++++++создание форм+++++++
class TransactionTypeForm(forms.ModelForm):
    class Meta:
        model = TransactionType
        fields = ["name"]
        


class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = ["name"]
       


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ["name", "transaction_type"]
        

class SubCategoryForm(forms.ModelForm):
    class Meta:
        model = SubCategory
        fields = ["name", "category"]
        


class TransactionForm(forms.ModelForm):
    date = forms.DateField(
        required=False, widget=forms.DateInput(attrs={"type": "date"})
    )

    class Meta:
        model = Transaction
        fields = (
            "date",
            "status",
            "transaction_type",
            "category",
            "subcategory",
            "summa",
            "comment",
        )
     
        # применение метода init   и фильтрация

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["date"].label = "Дата"
        self.fields["status"].label = "Статус"
        self.fields["transaction_type"].label = "Тип"
        self.fields["category"].label = "Категория"
        self.fields["subcategory"].label = "Подкатегория"
        self.fields["summa"].label = "Сумма"
        self.fields["comment"].label = "Комментарий"

        if "category" in self.data:
            try:
                category_id = int(self.data.get("category"))
                self.fields["subcategory"].queryset = SubCategory.objects.filter(
                    category_id=category_id
                )
            except (ValueError, TypeError):
                pass
        elif self.instance.pk and self.instance.category:
            self.fields["subcategory"].queryset = self.instance.category.subcategories.all()
            

    # проверка значений валидации
    def clean(self):
        cleaned_data = super().clean()
        transaction_type = cleaned_data.get("transaction_type")
        category = cleaned_data.get("category")
        subcategory = cleaned_data.get("subcategory")

        # +++++Бизнес правило №1++++++
        # +++++Пользователь не может выбрать подкатегорию, если она не связана с выбранной категорией++++++
        if category and subcategory and subcategory.category != category:
            raise forms.ValidationError(
                "Эта подкатегория не соотвествует выбранной категории"
            )

            # +++++Бизнес правило №2++++++
            # +++++Пользователь не может выбрать категорию, если она не относится к типу++++++
        if transaction_type and category and category.transaction_type != transaction_type:
            raise forms.ValidationError(
                "Эта категория не соотвествует типу, выберите другую"
            )

        return cleaned_data

main/views.py
from django.shortcuts import get_object_or_404, redirect, render


from main.forms import (
    CategoryForm,
    StatusForm,
    SubCategoryForm,
    TransactionForm,
    TransactionTypeForm,
)
from main.models import Category, Status, SubCategory, Transaction, TransactionType

# Create your views here.


# +++++++++Список+++++++++
def transaction_list(request):
    transactions = Transaction.objects.all().order_by("-date")

    date_to = request.GET.get("date_to")
    date_from = request.GET.get("date_from")
    status_id = request.GET.get("status")
    type_id = request.GET.get("type")
    category_id = request.GET.get("category")
    subcategory_id = request.GET.get("subcategory")

    # +++++++++++++фильтрация+++++++++
    if date_to:
        transactions = transactions.filter(date__lte=date_to)
    if date_from:
        transactions = transactions.filter(date__gte=date_from)
    if status_id and status_id.isdigit:
        transactions = transactions.filter(status_id=status_id)
    if type_id and type_id.isdigit:
        transactions = transactions.filter(transaction_type_id=type_id)
    if category_id and category_id.isdigit:
        transactions = transactions.filter(category_id=category_id)
    if subcategory_id and subcategory_id.isdigit:
        transactions = transactions.filter(subcategory_id=subcategory_id)

        # ++++++++++Извлекаем все обьекты+++++++++
    statuses = Status.objects.all()
    types = TransactionType.objects.all()
    categories = Category.objects.all()
    subcategories = SubCategory.objects.all()

    # ++++++++пишем контекст+++++++
    context = {
        "transactions": transactions,
        "statuses": statuses,
        "types": types,
        "categories": categories,
        "subcategories": subcategories,
        "filters": {
            "date_from": date_from,
            "date_to": date_to,
            "status": status_id,
            "type": type_id,
            "category": category_id,
            "subcategory": subcategory_id,
        },
    }
    return render(request, "cash-list.html", context)

    # ++++++++++создание записи++++++++++++


def transaction_create(request):
    if request.method == "POST":
        form = TransactionForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("main:transaction_list")
    else:
        form = TransactionForm()
    return render(request, "cash-form.html", {"form": form, "title": "Создание записи"})

    # ++++++++++++++редактирование записи++++++++++++++


def transaction_edit(request, pk):
    transaction = get_object_or_404(Transaction, pk=pk)
    if request.method == "POST":
        form = TransactionForm(request.POST, instance=transaction)
        if form.is_valid():
            form.save()
            return redirect("main:transaction_list")
    else:
        form = TransactionForm(instance=transaction)
    return render(
        request, "cash-form.html", {"form": form, "title": "Редактирование записи"}
    )

    #  ++++++++++++ удаление запси+++++++++++


def transaction_delete(request, pk):
    transaction = get_object_or_404(Transaction, pk=pk)
    if request.method == "POST":
        transaction.delete()
        return redirect("main:transaction_list")
    return render(
        request,
        "cash-form.html",
        {
            "transaction": transaction,
            "delete_confirm": True,
            "title": "Удаление записи",
        },
    )

    # ++++++++++++Справочники+++++++++++++++++


def guide_list(request):
    statuses = Status.objects.all()
    types = TransactionType.objects.all()
    categories = Category.objects.all()
    subcategories = SubCategory.objects.all()
    return render(
        request,
        "guide-list.html",
        {
            "statuses": statuses,
            "types": types,
            "categories": categories,
            "subcategories": subcategories,
        },
    )

    # ++++++++++++++Статус+++++++++++++++++++++
    # ++++++++++++++Создать+++++++++++++++++++++


def status_create(request):
    if request.method == "POST":
        form = StatusForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("main:guide_list")
    else:
        form = StatusForm()
    return render(
        request, "guide-form.html", {"form": form, "title": "Создание нового статуса"}
    )

    # ++++++++++++++Редактировать+++++++++++++++++++++


def status_edit(request, pk):
    status = get_object_or_404(Status, pk=pk)
    if request.method == "POST":
        form = StatusForm(request.POST, instance=status)
        if form.is_valid():
            form.save()
            return redirect("main:guide_list")
    else:
        form = StatusForm(instance=status)
    return render(
        request, "guide-form.html", {"form": form, "title": "Редактирование статуса"}
    )

    # ++++++++++++++Удалить+++++++++++++++++++++


def status_delete(request, pk):
    status = get_object_or_404(Status, pk=pk)
    if request.method == "POST":
        status.delete()
        return redirect("main:guide_list")
    return render(
        request,
        "guide-form.html",
        {"object": status, "delete_confirm": True, "title": "Удаление статуса"},
    )

    # +++++++++++++++Transactiontype++++++++++++++++++++
    # ++++++++++++++Создать+++++++++++++++++++++


def transtype_create(request):
    if request.method == "POST":
        form = TransactionTypeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("main:guide_list")
    else:
        form = TransactionTypeForm()
    return render(
        request, "guide-form.html", {"form": form, "title": "Создание  нового типа "}
    )

    # ++++++++++++++Редактировать+++++++++++++++++++++


def transtype_edit(request, pk):
    transtype = get_object_or_404(TransactionType, pk=pk)
    if request.method == "POST":
        form = StatusForm(request.POST, instance=transtype)
        if form.is_valid():
            form.save()
            return redirect("main:guide_list")
    else:
        form = TransactionTypeForm(instance=transtype)
    return render(
        request, "guide-form.html", {"form": form, "title": "Редактирование типа"}
    )

    # ++++++++++++++Удалить+++++++++++++++++++++


def transtype_delete(request, pk):
    transtype = get_object_or_404(TransactionType, pk=pk)
    if request.method == "POST":
        transtype.delete()
        return redirect("main:guide_list")
    return render(
        request,
        "guide-form.html",
        {"object": transtype, "delete_confirm": True, "title": "Удаление типа"},
    )

    # +++++++++++++++Категория++++++++++++++++++
    # ++++++++++++++Создать+++++++++++++++++++++


def category_create(request):
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("main:guide_list")
    else:
        form = CategoryForm()
    return render(request, "guide-form.html", {"form": form, "title": "Создание новой категории "},
    )


    # ++++++++++++++Редактировать+++++++++++++++++++++


def category_edit(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == "POST":
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            return redirect("main:guide_list")
    else:
        form = CategoryForm(instance=category)
    return render(
        request,
        "guide-form.html",
        {"form": form, "title": "Редактирование категории"},
    )

    # ++++++++++++++Удалить+++++++++++++++++++++


def category_delete(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == "POST":
        category.delete()
        return redirect("main:guide_list")
    return render(
        request,
        "guide-form.html",
        {"object": category, "delete_confirm": True, "title": "Удаление категории"},
    )

    # +++++++++++++++Подкатегория++++++++++++++++++
    # ++++++++++++++Создать+++++++++++++++++++++


def subcategory_create(request):
    if request.method == "POST":
        form = SubCategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("main:guide_list")
    else:
        form = TransactionTypeForm()
    return render(
        request,
        "guide-form.html",
        {"form": form, "title": "Создание новой подкатегории "},
    )

    # ++++++++++++++Редактировать+++++++++++++++++++++


def subcategory_edit(request, pk):
    subcategory = get_object_or_404(SubCategory, pk=pk)
    if request.method == "POST":
        form = StatusForm(request.POST, instance=subcategory)
        if form.is_valid():
            form.save()
            return redirect("main:guide_list")
    else:
        form = StatusForm(instance=subcategory)
    return render(
        request,
        "guide-form.html",
        {"form": form, "title": "Редактирование подкатегории "},
    )

    # ++++++++++++++Удалить+++++++++++++++++++++


def subcategory_delete(request, pk):
    subcategory = get_object_or_404(SubCategory, pk=pk)
    if request.method == "POST":
        subcategory.delete()
        return redirect("main:guide_list")
    return render(
        request,
        "guide-form.html",
        {
            "object": subcategory,
            "delete_confirm": True,
            "title": "Удаление подкатегории",
        },
    )

main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Переводы 💵💲</title>
                            <!--Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    
</head>
<body>
      <nav class="navbar" style="background-color: #e3f2fd;" data-bs-theme="light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url "main:transaction_list" %}">Приложение(cash_flow)</a>
          <div>
            <a class="nav link" href="{% url "main:transaction_create" %}">Создание записи</a>
            <a class="nav link" href="{% url "main:guide_list" %}">Справочники приложения</a>
          </div>
        </div>
      </nav>
      <div class='container'>
        {% block content %}
       
        {% endblock content %}
      </div>
                     <!--Javascript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>



</body>
</html>

main/templates/cash_form.html
{% extends "base.html" %}


{% block content %}
<h3 style="color:black">{{title}}</h3>
<form method="post" class="mb-4">
    {% csrf_token %}
    {{ form.as_p }}
    {% if delete_confirm %}
        <button type='submit' class= "btn btn-danger">Удалить запись</button>
        <a href="{% url "main:transaction_list" %}" class="btn btn-dark">Отмена</a>
    {% else %}
        <button type='submit' class= "btn btn-primary">Сохранить запись</button>
    {% endif %}
</form>
{% block footer %}


{% endblock footer %}
{% endblock content %}

main/templates/cash_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h4 style="color:blue;text-align:center;text-decoration:underline"> Движения денежных средств(ДДС)</h4>


        <!--  Форма записи данных -->  
<form  method="get" class="row lg-12" style="text-align:left;color:blue">
    <div class="col-12">
      <label class="form-label">Дата с:</label>
      <input type="date" name="date_from" class="form-control" value={{ filters.date_from}}>
    </div>
    <div class="col-12">
        <label class="form-label">Дата по:</label>
        <input type="date" name="date_to" class="form-control" value={{ filters.date_to}}>
    </div>
    <div class="col-12">
      <label class="form-label">Статус</label>
      
      <select name="status" class="form-select">
        <option value="">Все статусы переводов</option>
        <option value="">статус_1</option>
        <option value="">статус_2</option>
        <!--  Проверка фильтрация -->  
        {% for s in statuses %}
          <option value="{{ s.id }}" {% if filters.status == s.id|stringformat:"s" %}selected{% endif %}>{{ s.name }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="col-12">
        <label class="form-label">Тип транзакций</label>
        <select name="type" class="form-select">
          <option value="">Все типы транзакзиций</option>
          <option value="">тип_1</option>
          <option value="">тип_2</option>  
            <!--  Проверка фильтрация -->  
          {% for t in types %}
            <option value="{{ t.id }}" {% if filters.type == t.id|stringformat:"t" %}selected{% endif %}>{{ t.name }}</option>
          {% endfor %}
        </select>
      </div>
    <div class="col-12">
        <label class="form-label">Категория</label>
        <select name="category" class="form-select">
          <option value="">Все категории</option>
          <option value="">категория_1</option>
          <option value="">категория_2</option>
            <!--  Проверка фильтрация -->  
          {% for c in categories %}
            <option value="{{ c.id }}" {% if filters.status == c.id|stringformat:"c" %}selected{% endif %}>{{ c.name }}</option>
          {% endfor %}
        </select>  
    </div>
    <div class="col-12">
        <label class="form-label">Подкатегория</label>
        <select name="subcategory" class="form-select">
          <option value="">Все подкатегории</option>
          <option value="">Подкатегории_1</option>
          <option value="">подкатегория_2</option>
            <!--  Проверка фильтрация -->  
          {% for subc in subcategories %}
            <option value="{{ subc.id }}" {% if filters.status == subc.id|stringformat:"subc" %}selected{% endif %}>{{ subc.name }}</option>
          {% endfor %}
        </select>
    </div>
    <div class="col-12" style="margin:10px">
        <button  type="submit" class="btn btn-info" title="Просмотр записи по фильтрам">Фильтрация</button>
    </div>
</form>

<!--  Создание таблицы с данными -->  
<table class="table table-striped">
    <thead>
        <tr>
            <th style="border: 1px solid blue">Дата</th>
            <th style="border: 1px solid blue">Статус</th>
            <th style="border: 1px solid blue">Тип</th>
            <th style="border: 1px solid blue">Категория</th>
            <th style="border: 1px solid blue">Подкатегория</th>
            <th style="border: 1px solid blue">Сумма</th>
            <th style="border: 1px solid blue">Комментарий</th>
        </tr>
    </thead>
    <tbody> 
        <!--  написание цикла --> 
        {% for t in transactions %}
        <tr>
            <td>{{ t.date}}</td>
            <td>{{ t.status.name}}</td>
            <td>{{ t.transactions_type.name}}</td>
            <td>{{ t.category.name}}</td>
            <td>{{ t.subcategory.name }}</td>
            <td>{{ t.summa }}</td>
            <td>{{ t.comment }}</td>
            <td>
              <a href="{% url 'main:transaction_edit' t.id %}" class="btn btn-secondary" style="border: 1px solid black">отредактировать</a>
              <a href="{% url 'main:transaction_delete' t.id %}"  class="btn btn-danger" style="border: 1px solid black">Удалить</a>
            </td>
        </tr>    
        {% endfor %}
    </tbody>
</table>


{% block footer %}
<footer class="py-4 bg-primary">
    <div class="container">
        <p class="m-0 text-center text-white">Приложение/ Переводы 💵💲 разработано для студии IT-Solutions в 2025г</p>
    </div>
</footer>
{% endblock footer %}


{% endblock content %}

main/templates/guide_form.html
{{% extends "base.html" %}

{% block content %}

<h3>{{title}}</h3>
<form method="post" class="mb-4">
    {% csrf_token %}
    {{ form.as_p }}
    {% if delete_confirm %}
        <button type='submit' class= "btn btn-danger">Удалить данные</button>
        <a href="{% url "main:guide_list" %}" class="btn btn-dark">Отмена действия</a>
    {% else %}
        <button type='submit' class= "btn btn-primary">Сохранить</button>
        <a href="{% url "main:guide_list" %}" class='btn btn-secondary'>Вернуться назад </a>
    {% endif %}
</form>


{% block footer %}

{% endblock footer %}
{% endblock content %}

    

main/templates/guide_list.html
{% extends "base.html" %}
{% block content %}

<h1 style="color:blue;text-align:center;text-decoration:underline;font-style:oblique">Справочники:</h1>

<h4 style="color:blue;text-align:left;text-decoration:underline;font-style:oblique">Тип транзакции</h4>
<a href="{% url 'main:transtype_create' %}" class="btn btn-success btn-sm-mb-1">Добавить</a>
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                Имя операции
            </th>
        </tr>
    </thead> 
    <tbody>
        {% for t in types %}
            <tr>
                <td>
                    {{ t.id}}
                </td>
                <td>
                    {{ t.name}}
                </td>
                <td>
                    <a class="btn btn-secondary btn-sm mb-1" href="{% url "main:transtype_edit" t.id %}">Отредактировать</a>
                    <a class="btn btn-danger btn-sm mb-1" href="{% url "main:transtype_delete" t.id %}">Удалить</a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<h4 style="color:blue;text-align:left;text-decoration:underline;font-style:oblique"> Статус</h4>
<a href="{% url "main:status_create" %}" class="btn btn-success btn-sm mb-1">Добавить</a>
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                Имя операции
            </th>
        </tr>
    </thead>
    <tbody>
        {% for s in statuses %}
            <tr>
                <td>
                    {{ s.id}}
                </td>
                <td>
                    {{ s.name}}
                </td>
                <td>
                    <a class="btn btn-secondary btn-sm mb-1" href="{% url "main:status_edit" s.id %}">Отредактировать</a>
                    <a class="btn btn-danger btn-sm mb-1" href="{% url "main:status_delete" s.id %}">Удалить</a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<h4 style="color:blue;text-align:left;text-decoration:underline;font-style:oblique"> Категория</h4>
<a href="{% url "main:category_create" %}" class="btn btn-success btn-sm mb-1">Добавить</a>
<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Имя операции</th>
            <th>Тип транзакции</th>
        </tr>
    </thead>
    <tbody>
        {% for c in categories %}
        <tr>
            <td>{{ c.id }}</td>
            <td>{{ c.name }}</td>
            <td>{{ c.transaction_type.name }}</td>
            <td>
                <a class="btn btn-secondary btn-sm mb-1" href="{% url 'main:category_edit'  c.id %}">Отредактировать</a>
                <a class="btn btn-danger btn-sm mb-1" href="{% url 'main:category_delete'  c.id %}">Удалить</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>



<h4 style="color:blue;text-align:left;text-decoration:underline;font-style:oblique">Подкатегория</h4>
<a href="{% url "main:subcategory_create" %}" class="btn btn-success btn-sm mb-1">Добавить</a>
<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Имя операции</th>
            <th>Категория</th>
        </tr>
    </thead>
    <tbody>
        {% for subc in subcategories %}
        <tr>
            <td>{{ subc.id }}</td>
            <td>{{ subc.name }}</td>
            <td>{{ subc.category.name }}</td>
            <td>
                <a class="btn btn-secondary btn-sm mb-1" href="{% url 'main:subcategory_edit' subc.id %}">Отредактировать</a>
                <a class="btn btn-danger btn-sm mb-1" href="{% url 'main:subcategory_delete' subc.id %}">Удалить</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>



{% block footer %}
<footer class="py-4 bg-primary">
    <div class="container">
        <p class="m-0 text-center text-white">Приложение/ Переводы 💵💲 разработано для студии IT-Solutions в 2025г</p>
    </div>
</footer>
{% endblock footer %}
{% endblock content %}
{% endblock content %}